### ISSUE TITLE
Use canvas API

### ISSUE THREAD

**Issue by devsargam** [devsargam/SnakeGame#12]
Currently this game is based on DOM manipulation but it is not the best practice.
Using HTML canvas is much better.
So whole apps logic should be rewritten to support such changes.

**Comment by mantevian** [comment]
I'm familiar with canvas, so yes, I can work on this.

**Comment by devsargam** [comment]
@mantevian you can start working on this.

**Comment by mantevian** [comment]
I'm on it

**Comment by mantevian** [comment]
Should all text and the pause menu also be a part of canvas? Seems like a good job has been done on the pause menu already, so maybe there is no need to change it

**Comment by devsargam** [comment]
@mantevian thanks for your contribution. This has immensely improved the performance of code.
