### ISSUE TITLE
Splash Title Screen

### ISSUE THREAD

**Issue by devsargam** [devsargam/SnakeGame#14]
Title screen like in other games which comes when you pause the game by pressing escape.
Lets to view settings in ordered fashion and change themes

**Comment by thevinitgupta** [comment]
I would like to contribute this feature.
Could you please explain what things need to be done?

**Comment by devsargam** [comment]
GOALS ✨
* Opening screen like in most of games when visiting the webpage with `Play`, `Settings` and `Leaderboard`
* When user presses escapse while playing the game, it pauses and shows similar options as before but `Play` replaced by `Resume`
* `Settings` should be able to change `Theme` and `Difficulty`
* `Leaderboard` should include high score

**Comment by devsargam** [comment]
@thevinitgupta should I assign you?

**Comment by devsargam** [comment]
@thevinitgupta the repo went through some changes. @larsniet has enabled pause feature. Can you work through this?

**Comment by thevinitgupta** [comment]
Sure having the pause feature would help me a lot.

**Comment by thevinitgupta** [comment]
Can I start working on this?

**Comment by devsargam** [comment]
@thevinitgupta  yes you may start on this.

**Comment by thevinitgupta** [comment]
Thanks @devsargam. 
I have started working on it.
Could you please add the `hacktoberfest` tag to the issue?

**Comment by devsargam** [comment]
Done in https://github.com/devsargam/SnakeGame/pull/27
