### ISSUE TITLE
Seperate Files and Better Classes

### ISSUE THREAD

**Issue by devsargam** [devsargam/SnakeGame#26]
Currently, the code in this repository has all methods and properties in the same Board class.
According to convention, the code should be divided into more classes for better testing and readability.
The code should be extracted into different classes like `Snake`, `Board` and `Food`.
Also the functions used for utility should be extracted into seperate files too.

**Comment by IRSHIT033** [comment]
can u assign  me to this

**Comment by devsargam** [comment]
@IRSHIT033 I'll assign you

**Comment by devsargam** [comment]
@mantevian I agree with you. @IRSHIT033 might not be familiar with the use of canvas. Therefore you can also help in code restructure if you want to. Should I assign you too?

**Comment by IRSHIT033** [comment]
ok then I am working on restructuring first

**Comment by devsargam** [comment]
@IRSHIT033 are you working on it?

**Comment by devsargam** [comment]
@IRSHIT033 you didn't responded so I am assigning this to myself.
