### ISSUE TITLE
Add more themes

### ISSUE THREAD

**Issue by devsargam** [devsargam/SnakeGame#29]
more theme options that suit the project theme in /src/scripts/themes.js

**Comment by KanjiZain** [comment]
Please Assign this issue to me Thankyou

**Comment by devsargam** [comment]
@KanjiZain there you have it! Good luck!

**Comment by devsargam** [comment]
@KanjiZain are you working on this?

**Comment by devsargam** [comment]
@Tobshub I'll add you here

**Comment by Tobshub** [comment]
Something here :)
Thanks for having me!

**Comment by devsargam** [comment]
@Tobshub feel free work and create pr!

**Comment by secretSocrates** [comment]
Can you please assign me this issue? I have a couple of themes in my mind that I will add. Thanks.

**Comment by devsargam** [comment]
@secretSocrates here you go!
