### ISSUE TITLE
add a logo on the the title bar

### ISSUE THREAD

**Issue by rutvikk05** [devsargam/SnakeGame#30]
Every great webapp has an attractive logo. 
How about creating one for this game as well? 

I would like to work on this issue. Could you assign it hacktoberfest label?

**Comment by devsargam** [comment]
@rutvikk05 I've assigned you! good luck

**Comment by rutvikk05** [comment]
Thanks, @devsargam . I've created a PR for the same :D

**Comment by devsargam** [comment]
@rutvikk05 welcome. Feel free to star the project
