### ISSUE TITLE
improve UI of home screen 

### ISSUE THREAD

**Issue by rutvikk05** [devsargam/SnakeGame#37]
The Current UI of the home page looks pretty basic. You can optimise and beautify it.

**Comment by Anuran12** [comment]
I would like to work on this.. please assign it to me

**Comment by rutvikk05** [comment]
sure @Anuran12

**Comment by Anuran12** [comment]
Assign it to me please

**Comment by devsargam** [comment]
@Anuran12 go ahead! Hoping to see a eye catching experience

**Comment by Anuran12** [comment]
@devsargam 

![Screenshot_2022-10-12-16-34-09-69_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/104062485/195326679-ed19d73d-ce68-410b-8efb-f280168b1859.jpg)

I have to change the ui only for this portion. Right ?

**Comment by devsargam** [comment]
@Anuran12 use your frontend skills and edit the styles as you like. There is also another issue https://github.com/devsargam/SnakeGame/issues/38 which focuses on the thing you pointed!

**Comment by devsargam** [comment]
Resolved in #42
