### ISSUE TITLE
Beautify Splash-Screen

### ISSUE THREAD

**Issue by xstable** [devsargam/SnakeGame#38]
Splash screen looks a bit untidy.
I'd like to enhance this a bit to fit general Layout-Rules to look more professional

**Comment by devsargam** [comment]
@xstable I've assinged. If you like this project please :star:

**Comment by devsargam** [comment]
@xstable I suggest you take this issue after https://github.com/devsargam/SnakeGame/issues/37 has been resolved. You can improve on his design. Else you both will create a merge conflict.

**Comment by xstable** [comment]
ok, but seems the assigner remove it's assignment in the due-time

**Comment by devsargam** [comment]
@xstable yeah, it was closed and opened shortly.
