### ISSUE TITLE
Adding rule discription how to play

### ISSUE THREAD

**Issue by xstable** [devsargam/SnakeGame#39]
Sure, Snake is an well known easy game. 
But every game should have a short description what to do at least, and which keys are to use.

Please assign it to me, and I'll add it in a nice way.

**Comment by devsargam** [comment]
Great idea!

**Comment by jatin00000** [comment]
I had solved the above issue. https://github.com/devsargam/SnakeGame/pull/45
Please accept my Merge Request.

**Comment by devsargam** [comment]
@jatin00000 teaching how to play was supposed to be on website no on the readme

**Comment by jatin00000** [comment]
I had added "How to Play" on Website.
https://github.com/devsargam/SnakeGame/pull/52

**Comment by jatin00000** [comment]
I am sorry for the inconvenience caused by me. The pull request created by me earlier has a lot of resolve conflicts.
So, it would have been created a trouble.

**Comment by jatin00000** [comment]
So I am making this new pull request https://github.com/devsargam/SnakeGame/pull/56 .
I had created the menu as required. 
Please review and accept my pull request.
Please assign this new pull request with all the earlier tags.
Thank You

**Comment by devsargam** [comment]
@jatin00000 there was a lot of hussle. ATEOTD you did it :clinking_glasses: 
I will review the code tomorrow and merge it then.
