### ISSUE TITLE
Want to update README.md file and adding CODE_OF_CONDUCT file

### ISSUE THREAD

**Issue by sb-decoder** [devsargam/SnakeGame#41]
**Is your feature request related to a problem? Please describe.**
I want to add how to contribute section and also contributors profile into main README.md file and want to add Code of conduct file.

**Comment by sb-decoder** [comment]
@devsargam Do you want this? then assign this to me.

**Comment by devsargam** [comment]
@sb-decoder yeah sure

**Comment by sb-decoder** [comment]
Ok !

**Comment by devsargam** [comment]
@sb-decoder are you working on this???

**Comment by sb-decoder** [comment]
Yeah

**Comment by devsargam** [comment]
Done #55
