### ISSUE TITLE
website is not reflexive,

### ISSUE THREAD

**Issue by YugalPradhan** [devsargam/SnakeGame#44]
there should be score board at corner of the game that should display score.

**Comment by YugalPradhan** [comment]
@devsargam  assign me this issue , I will do it

**Comment by devsargam** [comment]
@YugalPradhan WDYM? There is a score board

**Comment by YugalPradhan** [comment]
ok I got the issue , it's not about scoreboard , it's about reflexive website , in my 14 inch laptap scoreboard is not visible, 
here is the screenshot-
![Screenshot (597)](https://user-images.githubusercontent.com/75770560/195366744-c8ad2854-8941-485d-8254-1cfb6864f4db.png)

**Comment by devsargam** [comment]
I also have a 14' laptop but it works fine.
![image](https://user-images.githubusercontent.com/76874341/195367432-02bd93b1-2d80-4a6d-984c-cf9522dc023e.png)

**Comment by devsargam** [comment]
@YugalPradhan have you got any idea. How to fix this?

**Comment by devsargam** [comment]
@xstable do you want to work on this?
