### ISSUE TITLE
[bug]: opposite direction only cause an crash if upwards

### ISSUE THREAD

**Issue by xstable** [devsargam/SnakeGame#46]
**Describe the bug**
It's not clear if the game should recognize if a user press the opposite direction.
Means if snake goes from right to left, and user press right, ...should in this case a crash happen?

Nevertheless if yes or not, it's a bug, because this only happends if snake goes from bottom to top, and user press `down arrow`

**To Reproduce**

1. snake direction to to
2. press down arrow at keyboard
3. Try the same with other directions (will not work)!

**Comment by devsargam** [comment]
@xstable thank you for your valuable bug report. <3
Should be an easy fix so I'll do it myself.

**Comment by devsargam** [comment]
fixed in #53
