### ISSUE TITLE
Put "game over" Message in the middle of the screen

### ISSUE THREAD

**Issue by xstable** [devsargam/SnakeGame#47]
Currently it looks like that:
![image](https://user-images.githubusercontent.com/1778068/195437599-0b086097-3584-4e2b-a541-ce5fe83a049b.png)

Put the notification of game over and restart game at the middle of the screen:

![image](https://user-images.githubusercontent.com/1778068/195437503-7b49cf8f-2667-4101-8f6d-b4f4a0b893a6.png)

**Comment by rodolfonei** [comment]
Hi, I would like to work on this one, please

**Comment by pikameow420** [comment]
Hello, I'd like to work on this issue.

**Comment by TanishqRinjay** [comment]
Hi, Can I work on this issue?

**Comment by thisisamish** [comment]
Hey! I am working on this issue. Please assign it to me.

**Comment by devsargam** [comment]
@TanishqRinjay, @pikameow420 and @rodolfonei I have already assigned someone else. Try to find something else in this repo to contribute. :D

**Comment by xstable** [comment]
@devsargam hey, it's my issue and I've created it. Why do you ssign it to another person? Don't get this!

**Comment by thisisamish** [comment]
> @devsargam hey, it's my issue and I've created it. Why do you asign it to another person? Don't get this!

Hey @xstable! I am sorry but you raised the issue but never asked to assign it to you. So I thought it was up for grabs and hence made my PR.

**Comment by devsargam** [comment]
> @devsargam hey, it's my issue and I've created it. Why do you asign it to another person? Don't get this!
> 

@xstable you never asked to assign it to you. @thisisamish has already made his pull request which is tells is first one ever. You were also working on other issues so I gave him the issue.
