### ISSUE TITLE
[bug]:  Website is not responsive.

### ISSUE THREAD

**Issue by SahilSingh177** [devsargam/SnakeGame#57]
# Issue: This website is not responsive. 

# Supporting Doc:
![Screenshot (159)](https://user-images.githubusercontent.com/96344003/195662095-0045e819-0e4b-47b5-86b3-2c21b9e9a5f3.png)

**Comment by annupriy** [comment]
I can help with this issue. If you're not working on it, Please assign this to me.

**Comment by SahilSingh177** [comment]
> I can help with this issue. If you're not working on it, Please assign this to me.

I am not the maintainer of this project, but if he allows, sure go for it!

**Comment by devsargam** [comment]
@annupriy @SahilSingh177 but does this really need to be responsive???
It is already unplayable on small devices because they lack keyboard.

**Comment by annupriy** [comment]
> @annupriy @SahilSingh177 but does this really need to be responsive??? It is already unplayable on small devices because they lack keyboard.

Can we add buttons( up, down, left, and right) to make it playable on small devices?

**Comment by devsargam** [comment]
@annupriy yeah, sure you can. The code base is getting slightly edited so wait for a day. :smiley_cat:

**Comment by annupriy** [comment]
Sure! Just let me know and assign this to me when that completes.

**Comment by devsargam** [comment]
@annupriy assigned you! Will let you know within a day or two. Happy hacking!!!

**Comment by devsargam** [comment]
@annupriy feel free to work on this. Currently the game is switched to canvas for rendering.
