### ISSUE TITLE
New theme

### ISSUE THREAD

**Issue by Tobshub** [devsargam/SnakeGame#58]
**Is your feature request related to a problem? Please describe.**
There are currently not enough themes available

**Describe the solution you'd like**
I want to add a particular theme that I have in mind.

**Additional context**
It's just one theme, but I think I would look good and fit the feel of the game a lot. It's a desert-style theme!

**Comment by devsargam** [comment]
@Tobshub this issue is duplicate of #29. If you want to I'll assign you on that issue.

**Comment by Tobshub** [comment]
@devsargam Oh okay, yes I'd like that please
