### ISSUE TITLE
High score feature

### ISSUE THREAD

**Issue by devsargam** [devsargam/SnakeGame#6]
This is self explanatory. If you have any queries feel free to comment down.

**Comment by mantevian** [comment]
Hello, I'd like to work on this! I actually haven't interacted with the local storage yet but it seems pretty easy with plain javascript, so it shouldn't be hard while still being a new experience 😄

**Comment by devsargam** [comment]
okay, I've assigned you.

**Comment by devsargam** [comment]
Thanks a lot.
