### ISSUE TITLE
[bug]: Fix the overflow of the `Game over` modal

### ISSUE THREAD

**Issue by inclinedadarsh** [devsargam/SnakeGame#61]
**Describe the bug**
After the game is over, the text in the `Game Over` modal overflows.

**To Reproduce**
1. Play the game and fail.
2. See error

**Expected behavior**
The text should not overflow.

**Screenshots or GIFs**
![image](https://user-images.githubusercontent.com/84132532/195841671-98629e36-9cde-43b0-ac72-b39f415a3955.png)

**Info (please complete the following information):**
 - Browser Chrome
 - Version 106.0.5249.119 (Official Build) (64-bit)

**Comment by inclinedadarsh** [comment]
I can fix this, please assign it to me.

**Comment by amardeep911** [comment]
Plz assign this to me

**Comment by devsargam** [comment]
@inclinedadarsh go ahead!

**Comment by devsargam** [comment]
resolved in #63
